name: Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: { branches: [main] }
  # Run this workflow once per day, at 10:15 UTC
  schedule: [{ cron: "15 10 * * *" }]
  # Run this workflow when triggered manually in GitHubâ€™s UI.
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Deploy to Observable Cloud
        # This parameter to `--message` will use the latest commit message
        run: npm run deploy -- --message "$(git log -1 --pretty=%s)"
        env:
          # Authentication information. See below for how to set this up.
          OBSERVABLE_TOKEN: ${{ secrets.OBSERVABLE_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 # peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  # deploy-pages:
  #   runs-on: ubuntu-latest
  #   # Run this job after the 'deploy' job finishes successfully
  #   needs: deploy
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         cache: npm
  #     - run: npm ci
  #     # - run: npm run build  # Build the project again (optional)
  #     - uses: actions/deploy-pages@v1
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         branch: gh-pages # Deploy to the 'gh-pages' branch
  #         folder: dist # Deploy content from the '/dist' directory
